# 02_train.pyが読むtrain設定ファイルです。

- name: Kappa_Small_o200k_ep50_drop0_LR1e3
  model: GPT2_Small
  tokenizer: o200k_base
  train_txt: kappa.txt
  test_txt: kappa_test.txt
  epochs: 50
  checkpoint_count: 10
  drop_rate: 0.0
  initial_lr: 0.0001
  peak_lr: 0.001

- name: Akutagawa_Small_o200k_ep50_drop01_LR1e3
  model: GPT2_Small
  tokenizer: o200k_base
  train_txt: Akutagawa.txt
  test_txt: Akutagawa_test.txt
  epochs: 50
  checkpoint_count: 10
  drop_rate: 0.1
  initial_lr: 0.0001
  peak_lr: 0.001

- name: Akutagawa_Medium_o200k_ep50_drop01_lr3e4
  model: GPT2_Medium
  tokenizer: o200k_base
  train_txt: Akutagawa.txt
  test_txt: Akutagawa_test.txt
  train_val_ratio: 0.95
  epochs: 50
  checkpoint_count: 10
  drop_rate: 0.1
  saved_checkpoint: ""
  initial_lr: 0.00003
  peak_lr: 0.0003

